# Generated by Django 3.1.1 on 2020-09-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbageCollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collectiondetails',
            table='collection_details',
        ),
    ]
