# Generated by Django 3.1.1 on 2020-09-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageCollection', '0002_auto_20200913_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiondetails',
            name='values',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
